# Github: https://github.com/Bllare
import re
import requests
from apis.sms.abstract import AbstractSmsProvider


class SmsMoorashin(AbstractSmsProvider):
    name = "SMS Moorashin"

    def send_request(self, phone: str) -> requests.Response:
        session = requests.Session()
        # Load a product page (or any page) to get the WP nonce and the token
        # The HAR shows referer to a product category page, so we'll use that.
        page = "https://moorashin.com/product-category/%D9%84%D9%88%D8%A7%D8%B2%D9%85-%D8%A2%D8%B1%D8%A7%DB%8C%D8%B4%DB%8C/"
        r = session.get(page, headers=self.get_headers(), timeout=10)
        # Extract X-WP-Nonce (usually in a meta tag or script)
        match = re.search(r'rest_nonce["\']?\s*:\s*["\']([^"\']+)["\']', r.text)
        if not match:
            # Try meta tag
            match = re.search(r'<meta name="rest-nonce" content="([^"]+)"', r.text)
        if not match:
            raise Exception("Could not extract WP nonce")
        wp_nonce = match.group(1)

        # Also need the 'token' in the payload (long hex string) – this might be generated by the plugin.
        # Possibly it's a combination of something. In the HAR it's a very long hex string.
        # We need to find it in the page source.
        token_match = re.search(r'token["\']?\s*:\s*["\']([a-f0-9]+)["\']', r.text)
        if not token_match:
            raise Exception("Could not extract token")
        token = token_match.group(1)

        post_url = "https://moorashin.com/wp-json/dlr/dlrSendCode"
        headers = self.get_headers()
        headers["Content-Type"] = "application/json"
        headers["X-WP-Nonce"] = wp_nonce
        payload = {
            "local_username": phone,
            "country_code": "98",
            "token": token
        }
        return session.post(post_url, json=payload, headers=headers, timeout=10)